### ISSUE TITLE
This is such a big issue, I can't forgive you.

### ISSUE THREAD

**Issue by TheModdedChicken** [SpicaApp/Spica-iOS#30]
Spica is too good of an application. smh Lea I can't believe you would overlook this massive issue. I really thought you would've been smart enough to realize this MASSIVE issue of Spica being too good of an application.

Shaking my head so hard right now you wouldn't even know. Unbelievable and unforgiveable.

**Comment by leabmgrt** [comment]
Oh god, sorry for that! 😭 Will fix asap, thanks for letting me know!

**Comment by TheModdedChicken** [comment]
That's what I thought >:(
